global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "streamlit-app"
    static_configs:
      - targets: ["host.docker.internal:8001"]

  # - job_name: "vllm-model"
  #   static_configs:
  #     - targets: ["host.docker.internal:8000"]