name: Deploy Streamlit App to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Export All GitHub Secrets to File
      env:
        SECRETS_JSON: ${{ toJson(secrets) }}
      run: |
        echo "$SECRETS_JSON" > secrets.json
        jq '.' secrets.json > formatted-secrets.json # For formatting and validation
        echo "Secrets exported to secrets.json"

    - name: Validate Exported Secrets
      run: cat formatted-secrets.json

    - name: Create Environment Variables from Secrets
      run: |
        jq -r 'to_entries[] | .key + "=" + (.value | tostring)' formatted-secrets.json > secrets.env
        set -o allexport
        source secrets.env
        set +o allexport
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to Azure CLI
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Build and push Docker image to ACR
    - name: Build and push Docker image
      run: |
        az acr login --name ${{ secrets.PSY_ACR_NAME }}
        docker build -t ${{ secrets.PSY_ACR_NAME }}.azurecr.io/streamlit-app:latest .
        docker push ${{ secrets.PSY_ACR_NAME }}.azurecr.io/streamlit-app:latest
    
    # Get AKS credentials
    - name: Get AKS credentials
      run: |
        az aks get-credentials --resource-group ${{ secrets.PSY_RESOURCE_GROUP }} --name ${{ secrets.PSY_CLUSTER_NAME }}

    # Create Kubernetes Secret
    - name: Create Kubernetes Secret
      run: |
        envsubst < k8s/secrets.yml > k8s/secrets-processed.yml
        kubectl apply -f k8s/secrets-processed.yml

    # Deploy the container
    - name: Deploy to AKS
      run: |
        kubectl replace -f k8s/deploy.yml
    
    - name: Restart deployment
      run: |
        kubectl rollout restart deployment psy-agent

        