name: Deploy Streamlit App to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Export All Secrets as Environment Variables Using Hashtable
      shell: pwsh
      env:
        SECRETS_CONTEXT: ${{ toJson(secrets) }}
      run: |
        # Convert SECRETS_CONTEXT JSON to a Hashtable
        $secrets = ($env:SECRETS_CONTEXT | ConvertFrom-Json | ConvertTo-Hashtable)

        # Export secrets as environment variables
        foreach ($key in $secrets.Keys) {
            $value = $secrets[$key]
            Write-Host "Exporting environment variable for: $key"
            [System.Environment]::SetEnvironmentVariable($key, $value, [System.EnvironmentVariableTarget]::Process)
        }

        # Debug: Print keys of all loaded secrets
        $secrets.Keys | ForEach-Object { Write-Host "Loaded secret: $_" }
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to Azure CLI
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Build and push Docker image to ACR
    - name: Build and push Docker image
      run: |
        az acr login --name ${{ secrets.PSY_ACR_NAME }}
        docker build -t ${{ secrets.PSY_ACR_NAME }}.azurecr.io/streamlit-app:latest .
        docker push ${{ secrets.PSY_ACR_NAME }}.azurecr.io/streamlit-app:latest
    
    # Get AKS credentials
    - name: Get AKS credentials
      run: |
        az aks get-credentials --resource-group ${{ secrets.PSY_RESOURCE_GROUP }} --name ${{ secrets.PSY_CLUSTER_NAME }}

    # Create Kubernetes Secret
    - name: Create Kubernetes Secret
      run: |
        envsubst < k8s/secrets.yml > k8s/secrets-processed.yml
        kubectl apply -f k8s/secrets-processed.yml

    # Deploy the container
    - name: Deploy to AKS
      run: |
        kubectl replace -f k8s/deploy.yml
    
    - name: Restart deployment
      run: |
        kubectl rollout restart deployment psy-agent

        